/**
 * Skyfall Ledger — <Amount />
 *
 * The lowest-level monetary primitive in Skyfall Ledger. Renders a value as
 * a typographically-correct money figure with:
 *
 *  - Tabular, lining numerals (`tnum lnum`) so digits stay column-aligned.
 *  - Locale + currency aware formatting via `Intl.NumberFormat.formatToParts`.
 *  - Differentially styled currency symbol and decimal portion.
 *  - Sign-driven semantic color (positive / negative / neutral / accent).
 *  - Accounting-style negatives (`($1,240.56)`) when requested.
 *  - A spelled-out screen-reader label generated by `srMoney`. The visual
 *    figure is `aria-hidden`; the SR-only label carries the meaning.
 *
 * It does NOT animate, does NOT compose with icons, and does NOT render a
 * "delta arrow" — those belong to higher-level components (`AmountDelta`,
 * `BalanceHero`) that compose this primitive.
 */
import * as React from 'react';
import type { AmountProps } from './Amount.types';
import { fontFamily, fontWeight as fontWeightTokens, numeric } from '../../tokens/typography';
import { srMoney, visuallyHidden } from '../../utils/a11y';

interface SizeSpec {
  fontSize: string;
  lineHeight: string;
  weight: number;
}

const SIZE_MAP: Record<NonNullable<AmountProps['size']>, SizeSpec> = {
  sm: { fontSize: '13px', lineHeight: '18px', weight: fontWeightTokens.medium },
  md: { fontSize: '14px', lineHeight: '20px', weight: fontWeightTokens.medium },
  lg: { fontSize: '20px', lineHeight: '28px', weight: fontWeightTokens.semibold },
  xl: { fontSize: '32px', lineHeight: '40px', weight: fontWeightTokens.semibold },
  hero: { fontSize: '56px', lineHeight: '60px', weight: fontWeightTokens.semibold },
};

const TONE_COLOR: Record<
  Exclude<NonNullable<AmountProps['tone']>, 'auto'>,
  string
> = {
  neutral: 'var(--ledger-color-text-primary)',
  positive: 'var(--ledger-color-positive)',
  negative: 'var(--ledger-color-negative)',
  accent: 'var(--ledger-color-text-accent)',
  muted: 'var(--ledger-color-text-muted)',
};

const resolveTone = (
  tone: NonNullable<AmountProps['tone']>,
  value: number,
): keyof typeof TONE_COLOR => {
  if (tone !== 'auto') return tone;
  if (!Number.isFinite(value) || value === 0) return 'neutral';
  return value > 0 ? 'positive' : 'negative';
};

const resolveSignDisplay = (
  sign: NonNullable<AmountProps['sign']>,
): 'auto' | 'always' | 'never' | 'exceptZero' => {
  switch (sign) {
    case 'always':
      return 'exceptZero';
    case 'never':
      return 'never';
    case 'accounting':
      // We strip the minus and wrap in parens ourselves.
      return 'never';
    case 'auto':
    default:
      return 'auto';
  }
};

const resolveFractionDigits = (
  decimals: NonNullable<AmountProps['decimals']>,
): { min: number | undefined; max: number | undefined } => {
  if (decimals === 'auto') return { min: undefined, max: undefined };
  if (decimals === 'hide') return { min: 0, max: 0 };
  return { min: decimals, max: decimals };
};

export const Amount: React.FC<AmountProps> = ({
  value,
  currency = 'USD',
  locale = 'en-US',
  size = 'md',
  tone = 'neutral',
  sign = 'auto',
  decimals = 'auto',
  compact = false,
  weight,
  dimDecimals = false,
  dimSymbol = false,
  className,
  style,
  ariaLabel,
}) => {
  const sizeSpec = SIZE_MAP[size];
  const resolvedTone = resolveTone(tone, value);
  const fractionDigits = resolveFractionDigits(decimals);
  const isInvalid = !Number.isFinite(value);
  const isNegative = Number.isFinite(value) && value < 0;
  const useAccountingNegative = sign === 'accounting' && isNegative;

  // For accounting mode we format the absolute value and wrap in parens
  // ourselves. Intl supports `currencySign: 'accounting'` but it varies by
  // locale and not all locales return parentheses, so we render explicitly.
  const formatValue = useAccountingNegative ? Math.abs(value) : value;

  const formatter = React.useMemo(() => {
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency,
      notation: compact ? 'compact' : 'standard',
      compactDisplay: compact ? 'short' : undefined,
      signDisplay: resolveSignDisplay(sign),
      minimumFractionDigits: fractionDigits.min,
      maximumFractionDigits: fractionDigits.max,
    });
  }, [
    locale,
    currency,
    compact,
    sign,
    fractionDigits.min,
    fractionDigits.max,
  ]);

  const parts = React.useMemo(
    () => (isInvalid ? null : formatter.formatToParts(formatValue)),
    [formatter, formatValue, isInvalid],
  );

  const fontWeight = weight
    ? fontWeightTokens[weight]
    : sizeSpec.weight;

  const wrapperStyle: React.CSSProperties = {
    display: 'inline-flex',
    alignItems: 'baseline',
    fontFamily: size === 'xl' || size === 'hero' ? fontFamily.display : fontFamily.sans,
    fontSize: sizeSpec.fontSize,
    lineHeight: sizeSpec.lineHeight,
    fontWeight,
    color: TONE_COLOR[resolvedTone],
    fontFeatureSettings: numeric.tabular,
    fontVariantNumeric: 'tabular-nums lining-nums',
    letterSpacing: size === 'xl' || size === 'hero' ? '-0.02em' : 'normal',
    whiteSpace: 'nowrap',
    ...style,
  };

  const srLabel =
    ariaLabel ??
    (isInvalid ? 'amount unavailable' : srMoney(value, { currency, locale }));

  if (isInvalid || !parts) {
    return (
      <span className={className} style={wrapperStyle} aria-label={srLabel}>
        <span aria-hidden="true">—</span>
      </span>
    );
  }

  // Walk Intl parts and apply differential styling. We split into three
  // visual buckets: currency symbol, integer/group/sign, fraction (decimal +
  // digits). The fraction bucket can render dimmer for the "$1,284.52"
  // hero treatment where the cents are de-emphasized.
  const symbolColor = dimSymbol ? 'var(--ledger-color-text-muted)' : undefined;
  const fractionColor = dimDecimals ? 'var(--ledger-color-text-muted)' : undefined;

  // Group consecutive fraction parts (decimal + fraction) so they share one span.
  type Bucket = 'symbol' | 'main' | 'fraction';
  const bucketOf = (type: Intl.NumberFormatPart['type']): Bucket => {
    if (type === 'currency') return 'symbol';
    if (type === 'decimal' || type === 'fraction') return 'fraction';
    return 'main';
  };

  const grouped: Array<{ bucket: Bucket; text: string }> = [];
  for (const part of parts) {
    const bucket = bucketOf(part.type);
    const last = grouped[grouped.length - 1];
    if (last && last.bucket === bucket) {
      last.text += part.value;
    } else {
      grouped.push({ bucket, text: part.value });
    }
  }

  return (
    <span className={className} style={wrapperStyle}>
      {/* Visually-rendered figure — hidden from AT */}
      <span aria-hidden="true" style={{ display: 'inline-flex', alignItems: 'baseline' }}>
        {useAccountingNegative && <span>(</span>}
        {grouped.map((g, i) => {
          if (g.bucket === 'symbol') {
            return (
              <span key={i} style={{ color: symbolColor }}>
                {g.text}
              </span>
            );
          }
          if (g.bucket === 'fraction') {
            return (
              <span key={i} style={{ color: fractionColor }}>
                {g.text}
              </span>
            );
          }
          return <span key={i}>{g.text}</span>;
        })}
        {useAccountingNegative && <span>)</span>}
      </span>
      {/* Spelled-out screen-reader label */}
      <span style={visuallyHidden}>{srLabel}</span>
    </span>
  );
};
