/**
 * Skyfall Ledger — Accessibility helpers
 *
 * Screen-reader-friendly money labels. Browser SR pronunciation of currency
 * symbols is unreliable, so any monetary surface should pair its visual
 * value with a spelled-out aria-label generated by `srMoney`.
 */
import type { CSSProperties } from 'react';

export interface SrMoneyOptions {
  currency?: string;
  locale?: string;
}

/**
 * Convert a number into a human-readable money phrase intended for
 * `aria-label` and `aria-live` regions.
 *   1240.56 → "one thousand two hundred forty US dollars and 56 cents"
 *   -42.10  → "minus 42 US dollars and 10 cents"
 *
 * Uses Intl.NumberFormat with `currencyDisplay: "name"` so currencies are
 * spelled out per locale automatically.
 */
export const srMoney = (
  value: number,
  { currency = 'USD', locale = 'en-US' }: SrMoneyOptions = {},
): string => {
  if (!Number.isFinite(value)) return 'amount unavailable';
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency,
    currencyDisplay: 'name',
    signDisplay: 'auto',
  }).format(value);
};

/** Hidden visually but available to AT — apply with `style={visuallyHidden}` */
export const visuallyHidden: CSSProperties = {
  position: 'absolute',
  width: '1px',
  height: '1px',
  padding: 0,
  margin: '-1px',
  overflow: 'hidden',
  clip: 'rect(0,0,0,0)',
  whiteSpace: 'nowrap',
  border: 0,
};
